#!/bin/sh
#
# start stop daemon for CentOS
#
# chkconfig: - 64 36
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 2 3 4 6
# Required-Start:
# description: start stop daemon for CentOS
# processname: python
# pidfile: /var/run/shudder/shudder.pid
# lockfile: /var/run/shudder/shudder.pid.lock

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

#!/bin/sh
# chkconfig: 123456 90 10
#
APPNAME="shudder"
APPBIN="python"
APPARGS="-m shudder.__main__"
PIDFILE="/var/run/shudder/shudder.pid"

start() {
    if [ -f /etc/profile ]; then
        source /etc/profile
    fi
    if [ -f $PIDFILE ]; then
      pid=`cat $PIDFILE`
      is_running=`ps -elf | grep $pid`
    fi
    if [ -n "$is_running" ]; then
      echo "App $APPNAME is already started."
    else
      $APPBIN $APPARGS
      echo "Started $APPNAME using config from $SHUDDER_CONFIG_FILE."
    fi
}

stop() {
    if [ -f $PIDFILE ]; then
      pid=`cat $PIDFILE`
      echo "Stopping $APPNAME with pid $pid..."
      kill $pid
      if [ $? -eq "0" ]; then
        rm -f $PIDFILE
      fi
      echo "Stopped $APPNAME."
    else
      echo "$APPNAME is not running."
    fi
}

status() {
  if [ -f $PIDFILE ]; then
      pid=`cat $PIDFILE`
      is_running=`ps -elf | grep $pid`
  fi
  if [ -n "$is_running" ]; then
    echo "$APPNAME is running."
  else
    echo "$APPNAME is not running."
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: /etc/init.d/$APPNAME {start|stop|restart|status}"
    exit 1
esac
exit 0
